Repository SOPT-all/36-COLLABORATION-WEB-WATCHAPEDIA, pull requests merged in 2025-05, with the labels that each got.

#5 [Init/#4] 프로젝트 초기 생성
  .gitignore
  next.config.ts
  package.json
  src/app/layout.tsx
  src/app/page.tsx
  src/app/styles.css.ts
  src/styles/global.css.ts
  src/styles/layers.css.ts
  src/styles/reset.css.ts
  src/styles/styles.css.ts
  tsconfig.json
  yarn.lock
Labels: ⚙️Environment, 🩵 정은

#7 [Init/#6] Prettier, ESLint 설정
  .eslintrc.json
  .prettierrc
  package.json
  yarn.lock
Labels: ⚙️Environment, 💜 혜린

#8 [Init/#3 ]GitHub action 설정
  .github/auto_assign.yml
  .github/workflows/github-actions-demo.yml
  .github/workflows/node.js.yml
  .gitignore
  next.config.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/app/styles.css.ts
  src/styles/global.css.ts
  src/styles/layers.css.ts
  src/styles/reset.css.ts
  src/styles/styles.css.ts
  tsconfig.json
Labels: ⚙️Environment, 윤지

#9 Revert "Merge pull request #8 from SOPT-all/init/#3/github-action"
  .github/auto_assign.yml
  .github/workflows/github-actions-demo.yml
  .github/workflows/node.js.yml
  .gitignore
  next.config.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/app/styles.css.ts
  src/styles/global.css.ts
  src/styles/layers.css.ts
  src/styles/reset.css.ts
  src/styles/styles.css.ts
  tsconfig.json
Labels: 🐞 Bug, ⚙️Environment, 정은

#11 [Feature/#10] 스타일 초기 설정
  src/app/layout.tsx
  src/app/page.tsx
  src/app/styles.css.ts
  src/styles/global.css.ts
  src/styles/text.css.ts
  src/styles/theme.css.ts
Labels: ⚙️Environment, 서연

#13 [Refactor/#12] 스타일 초기화 리팩토링
  src/app/page.tsx
  src/app/styles.css.ts
  src/styles/global.css.ts
  src/styles/styles.css.ts
  src/styles/text.css.ts
  src/styles/theme.css.ts
Labels: 🔨 Refactor, 서연

#20 [Init/#19] svgr 세팅
  next.config.ts
  package.json
  public/icons/ic_search.svg
  src/app/asset/svg/IcSearch.tsx
  src/app/asset/svg/index.ts
  types/svg.d.ts
  yarn.lock
Labels: ⚙️Environment, 윤지

#24 [Feat/#22] 라우팅 설정 및 svgr 스크립트 추가
  package.json
  public/icons/Star.svg
  src/app/content/[id]/page.tsx
  src/app/content/[id]/review/page.tsx
  src/app/content/recommend/page.tsx
  src/app/home/page.tsx
  src/app/page.tsx
  src/assets/svg/IcSearch.tsx
  src/assets/svg/Star.tsx
  src/assets/svg/index.ts
  src/shared/constants/path.ts
Labels: ✨ Feature, ⚙️Environment, 정은

#31 [Feat/#21] 홈 토글 컴포넌트 추가
  src/shared/components/HomeToggle/HomeToggle.css.ts
  src/shared/components/HomeToggle/HomeToggle.tsx
Labels: ✨ Feature, 혜린

#37 [Refactor/#36] Pretendard 폰트 적용
  src/app/layout.tsx
  src/app/styles.css.ts
Labels: 🔨 Refactor, ⚙️Environment, 정은

#25 [Feat/#18] 리뷰칩 컴포넌트 추가
  package.json
  src/shared/components/ReviewChip/ReviewChip.css.ts
  src/shared/components/ReviewChip/ReviewChip.tsx
  yarn.lock
Labels: ✨ Feature, 정은

#34 [Feat/#32] 스포일러 토글 버튼 추가
  src/shared/components/SpoilerToggle/SpoilerToggle.css.ts
  src/shared/components/SpoilerToggle/SpoilerToggle.tsx
Labels: ✨ Feature, 혜린

#29 [Feat/#28] 텍스트필드 컴포넌트 생성
  src/shared/components/TextField/TextField.css.ts
  src/shared/components/TextField/TextField.tsx
Labels: ✨ Feature, 정은

#17 [Feat/#15] 버튼 컴포넌트 추가
  src/shared/components/Button/Button.css.ts
  src/shared/components/Button/Button.tsx
Labels: ✨ Feature, 정은

#33 [Feat/#30] 헤더구현
  src/assets/img/watchapedia.png
  src/shared/components/HomeToggle/HomeToggle.tsx
  src/shared/constants/Header/Header.css.ts
  src/shared/constants/Header/Header.tsx
  src/shared/constants/Header/Tab.ts
Labels: ✨ Feature, 윤지

#40 [Feat/#39] 컨텐츠 조회 페이지 레이아웃 설정 및 고정 레이아웃 정의
  src/app/content/[id]/components/HeaderSection/HeaderSection.css.ts
  src/app/content/[id]/components/HeaderSection/HeaderSection.tsx
  src/app/content/[id]/layout.css.ts
  src/app/content/[id]/layout.tsx
  src/app/styles.css.ts
Labels: ✨ Feature, 정은

#35 [Feat/#14] 캐러셀 구현
  package.json
  public/images/banner/img-main-banner-1.png
  public/images/banner/img-main-banner-2.png
  public/images/banner/img-main-banner-3.png
  public/images/banner/img-main-banner-4.png
  public/images/banner/img-watcha-circle.png
  src/app/home/page.tsx
  src/shared/components/Carousel/Carousel.css.ts
  src/shared/components/Carousel/Carousel.tsx
  yarn.lock
Labels: ✨ Feature, 서연

#43 [Feat/#39] 컨텐츠 조회(view2) 정보 섹션 구현
  public/icons/back.svg
  public/icons/share.svg
  public/images/info_top.png
  public/images/watcha.png
  public/images/wavve.png
  src/app/content/[id]/components/info/InfoContent/InfoContent.css.ts
  src/app/content/[id]/components/info/InfoContent/InfoContent.tsx
  src/app/content/[id]/components/info/InfoHeader/InfoHeader.css.ts
  src/app/content/[id]/components/info/InfoHeader/InfoHeader.tsx
  src/app/content/[id]/page.tsx
  src/app/content/[id]/sections/info/InfoSection.css.ts
  src/app/content/[id]/sections/info/InfoSection.tsx
  src/assets/img/info_top.png
  src/assets/svg/Back.tsx
  src/assets/svg/Share.tsx
  src/assets/svg/index.ts
  src/mocks/detail.json
  src/mocks/index.ts
  src/shared/types/detail.ts
Labels: ✨ Feature, 정은

#42 [Feat/#41] ad 위젯 구현
  public/images/ad/img_ad_1.png
  public/images/ad/img_ad_2.png
  public/images/ad/img_watchapedia_sm.png
  public/images/banner/img_main_banner_1.png
  public/images/banner/img_main_banner_2.png
  public/images/banner/img_main_banner_3.png
  public/images/banner/img_main_banner_4.png
  public/images/banner/img_watcha_circle.png
  src/app/home/page.tsx
  src/shared/components/Button/Button.css.ts
  src/shared/components/Carousel/Carousel.tsx
  src/shared/components/Header/Header.css.ts
  src/shared/components/Header/Header.tsx
  src/shared/components/Header/Tab.ts
  src/shared/components/HomeToggle/HomeToggle.tsx
  src/shared/widget/Ad/Ad.css.ts
  src/shared/widget/Ad/Ad.tsx
Labels: ✨ Feature, 서연

#48 [Feat/#47] view1 코멘트 컴포넌트
  public/icons/ic_comment.svg
  public/icons/ic_like.svg
  public/icons/ic_profile_circle.svg
  public/icons/ic_star.svg
  public/icons/ic_star_empty.svg
  public/images/view1/img_comment_poster.png
  src/app/home/components/Section.css.ts
  src/app/home/components/Section.tsx
  src/app/home/components/SectionHeader.css.ts
  src/app/home/components/TrendingComment/TrendingComment.css.ts
  src/app/home/components/TrendingComment/TrendingComment.tsx
  src/app/home/page.tsx
  src/app/styles.css.ts
  src/assets/svg/IcComment.tsx
  src/assets/svg/IcLike.tsx
  src/assets/svg/IcProfileCircle.tsx
  src/assets/svg/IcStar.tsx
  src/assets/svg/IcStarEmpty.tsx
  src/assets/svg/index.ts
  src/mocks/index.ts
  src/mocks/trendingComment.json
Labels: ✨ Feature, 서연

#50 [Feat/#49] view1 이벤트 컴포넌트 구현
  public/images/view1/img_event.png
  src/app/home/components/Event/Event.css.ts
  src/app/home/components/Event/Event.tsx
  src/app/home/page.tsx
  src/assets/svg/IcRight.tsx
Labels: ✨ Feature, 서연

#52 [Feat/#51] view2 별점 그래프 컴포넌트 구현
  public/icons/ic_graph_star.svg
  src/app/content/[id]/components/StarGraph/GraphBar/GraphBar.css.ts
  src/app/content/[id]/components/StarGraph/GraphBar/GraphBar.tsx
  src/app/content/[id]/components/StarGraph/GraphTextContent/GraphTextContent.css.ts
  src/app/content/[id]/components/StarGraph/GraphTextContent/GraphTextContent.tsx
  src/app/content/[id]/components/StarGraph/StarGraph.css.ts
  src/app/content/[id]/components/StarGraph/StarGraph.tsx
  src/app/content/[id]/sections/info/InfoSection.tsx
  src/assets/svg/IcGraphStar.tsx
  src/assets/svg/index.ts
Labels: ✨ Feature, 혜린

#66 [Feat/#65] 컬렉션 섹션 구현
  public/images/view2/collection1.png
  public/images/view2/collection2.png
  public/images/view2/collection3.png
  public/images/view2/collection4.png
  public/images/view2/collection5.png
  public/images/view2/collection6.png
  public/images/view2/collection7.png
  public/images/view2/collection8.png
  src/app/content/[id]/page.tsx
  src/app/content/[id]/sections/collection/CollectionSection.css.ts
  src/app/content/[id]/sections/collection/CollectionSection.tsx
Labels: ✨ Feature, 정은

#56 [Feature/#54] view2 출연/제작 컴포넌트 구현
  public/images/view2/cast_1.png
  public/images/view2/cast_2.png
  public/images/view2/cast_3.png
  src/app/content/[id]/components/CastAndCrew/CastAndCrew.css.ts
  src/app/content/[id]/components/CastAndCrew/CastAndCrew.tsx
  src/app/content/[id]/components/CastAndCrew/CastAndCrewField/CastAndCrewField.css.ts
  src/app/content/[id]/components/CastAndCrew/CastAndCrewField/CastAndCrewField.tsx
Labels: ✨ Feature, 혜린

#58 [Feature/#57] view2 Comment 컴포넌트 구현
  public/icons/ic_comment_star.svg
  public/icons/icon_comment.svg
  public/icons/icon_like.svg
  src/app/content/[id]/components/Comment/Comment.css.ts
  src/app/content/[id]/components/Comment/Comment.tsx
  src/app/content/[id]/components/Comment/CommentBottom/CommentBottom.css.ts
  src/app/content/[id]/components/Comment/CommentBottom/CommentBottom.tsx
  src/app/content/[id]/components/Comment/CommentContent/CommentContent.css.ts
  src/app/content/[id]/components/Comment/CommentContent/CommentContent.tsx
  src/app/content/[id]/components/Comment/CommentHeader/ComentHeader.tsx
  src/app/content/[id]/components/Comment/CommentHeader/CommentHeader.css.ts
  src/assets/svg/IcCommentStar.tsx
  src/assets/svg/IconComment.tsx
  src/assets/svg/IconLike.tsx
  src/assets/svg/index.ts
  src/mocks/comment.json
  src/mocks/index.ts
Labels: ✨ Feature, 혜린

#60 [Feature/#59] view2 매거진 컴포넌트 구현
  public/icons/ic_magazine_logo.svg
  public/images/view2/magazine_1.png
  public/images/view2/magazine_2.png
  src/app/content/[id]/components/Magazine/Magazine.css.ts
  src/app/content/[id]/components/Magazine/Magazine.tsx
  src/app/content/[id]/components/Magazine/MagazineField/MagazineField.css.ts
  src/app/content/[id]/components/Magazine/MagazineField/MagazineField.tsx
  src/assets/svg/IcMagazineLogo.tsx
  src/assets/svg/index.ts
Labels: ✨ Feature, 혜린

#64 [Feat/#63] 갤러리 및 동영상 섹션 구현
  public/icons/icon_play.svg
  public/images/gallery1.png
  public/images/gallery2.png
  public/images/img_vid_1.png
  src/app/content/[id]/page.tsx
  src/app/content/[id]/sections/gallery/GallerySection.css.ts
  src/app/content/[id]/sections/gallery/GallerySection.tsx
  src/app/content/[id]/sections/video/VideoSection.css.ts
  src/app/content/[id]/sections/video/VideoSection.tsx
  src/assets/svg/IconPlay.tsx
  src/assets/svg/index.ts
Labels: ✨ Feature, 정은

#53 [Feat/#46]/view1 매거진 컴포넌트
  public/images/img_watcha_circle.png
  public/images/view1/img_magazine.png
  src/app/home/components/Magazine/MagazineCard.css.ts
  src/app/home/components/Magazine/MagazineCard.tsx
  src/app/home/components/Magazine/MagazineCarousel.css.ts
  src/app/home/components/Magazine/MagazineCarousel.tsx
  src/app/home/page.tsx
  src/mocks/index.ts
  src/mocks/magazine.json
  src/shared/components/Carousel/Carousel.tsx
Labels: ✨ Feature, 서연

#70 [Refactor/#69] View2 info1 섹션 연결
  src/app/content/[id]/components/StarGraph/GraphBar/GraphBar.css.ts
  src/app/content/[id]/components/StarGraph/GraphBar/GraphBar.tsx
  src/app/content/[id]/components/StarGraph/GraphTextContent/GraphTextContent.css.ts
  src/app/content/[id]/components/StarGraph/GraphTextContent/GraphTextContent.tsx
  src/app/content/[id]/components/StarGraph/StarGraph.css.ts
  src/app/content/[id]/components/StarGraph/StarGraph.tsx
  src/app/content/[id]/components/evaluation/Rating/Rating.css.ts
  src/app/content/[id]/components/evaluation/Rating/Rating.tsx
  src/app/content/[id]/components/evaluation/ReactionButtons/ReactionButtons.css.ts
  src/app/content/[id]/page.tsx
  src/app/content/[id]/sections/descriptionSection/DescriptionSection.css.ts
  src/app/content/[id]/sections/evaluation/EvaluationSection.css.ts
  src/app/content/[id]/sections/evaluation/EvaluationSection.tsx
  src/app/content/[id]/sections/graph/GraphSection.css.ts
  src/app/content/[id]/sections/graph/GraphSection.tsx
  src/app/content/[id]/styles.css.ts
  src/shared/components/Button/Button.css.ts
  src/shared/components/Button/Button.tsx
  src/shared/widget/Ad/Ad.css.ts
  src/shared/widget/Ad/Ad.tsx
Labels: 🔨 Refactor, 정은

#68 [Feat/#38] 영화 위젯
  public/icons/ic_plus.svg
  public/icons/ic_star.svg
  public/icons/ic_watcha_black.svg
  public/icons/ic_watcha_white.svg
  public/img/poster.png
  src/app/movie/page.tsx
  src/assets/svg/IcPlus.tsx
  src/assets/svg/IcRight.tsx
  src/assets/svg/IcStar.tsx
  src/assets/svg/IcWatchaBlack.tsx
  src/assets/svg/IcWatchaWhite.tsx
  src/assets/svg/index.ts
  src/shared/widget/MovieCard/MovieCard.css.ts
  src/shared/widget/MovieCard/MovieCard.tsx
  src/shared/widget/MovieCard/MovieCard.types.ts
  src/shared/widget/MovieCard/MovieMock.ts
  src/shared/widget/MovieCard/_components/Action.tsx
  src/shared/widget/MovieCard/_components/Badge.tsx
  src/shared/widget/MovieCard/_components/MovieCardTags.tsx
  src/shared/widget/MovieCard/_components/Poster.tsx
  src/shared/widget/MovieCard/_components/Star.tsx
  src/shared/widget/MovieCard/_components/SubInfo.tsx
  src/shared/widget/MovieCard/index.ts
Labels: ✨ Feature, 윤지

#75 [Feat/#67] View2 비슷한 콘텐츠 섹션 구현
  public/images/view2/similar1.png
  public/images/view2/similar2.png
  public/images/view2/similar3.png
  public/images/view2/similar4.png
  public/images/view2/similar5.png
  public/images/view2/similar6.png
  public/images/view2/similar7.png
  public/images/view2/similar8.png
  public/images/view2/similar9.png
  src/app/content/[id]/components/Similar/SimilarContentCard.css.ts
  src/app/content/[id]/components/Similar/SimilarContentCard.tsx
  src/app/content/[id]/page.tsx
  src/app/content/[id]/sections/similar/SimilarSection.css.ts
  src/app/content/[id]/sections/similar/SimilarSection.tsx
Labels: ✨ Feature, 정은

#72 [Refactor/#69] View2 info2 섹션 연결
  src/app/content/[id]/components/CastAndCrew/CastAndCrew.css.ts
  src/app/content/[id]/components/CastAndCrew/CastAndCrew.tsx
  src/app/content/[id]/components/CastAndCrew/CastAndCrewField.css.ts
  src/app/content/[id]/components/CastAndCrew/CastAndCrewField.tsx
  src/app/content/[id]/components/CastAndCrew/CastAndCrewField/CastAndCrewField.css.ts
  src/app/content/[id]/components/CastAndCrew/CastAndCrewField/CastAndCrewField.tsx
  src/app/content/[id]/components/Comment/Comment.tsx
  src/app/content/[id]/components/Comment/CommentBottom/CommentBottom.css.ts
  src/app/content/[id]/components/Comment/CommentContent/CommentContent.css.ts
  src/app/content/[id]/components/Comment/CommentHeader/CommentHeader.tsx
  src/app/content/[id]/components/HeaderSection/HeaderSection.css.ts
  src/app/content/[id]/components/Magazine/Magazine.css.ts
  src/app/content/[id]/components/Magazine/MagazineField.css.ts
  src/app/content/[id]/components/Magazine/MagazineField.tsx
  src/app/content/[id]/page.tsx
  src/app/content/[id]/sections/castAndCrew/CastAndCrewSection.tsx
  src/app/content/[id]/sections/comment/CommentSection.css.ts
  src/app/content/[id]/sections/comment/CommentSection.tsx
  src/app/content/[id]/sections/magazine/MagazineSection.css.ts
  src/app/content/[id]/sections/magazine/MagazineSection.tsx
  src/app/content/[id]/styles.css.ts
  src/mocks/comment.json
Labels: 🔨 Refactor, 정은

#86 [Fix/#83] 배포 오류 - 이전 캐시 삭제
  src/app/content/[id]/components/evaluation/LabelContainer/LabelContent.css.ts
  src/app/content/[id]/components/evaluation/LabelContainer/LabelContent.tsx
  src/app/content/[id]/components/evaluation/PreferTag/PreferTag.css.ts
  src/app/content/[id]/components/evaluation/PreferTag/PreferTag.tsx
  src/app/content/[id]/components/evaluation/RateView/RateList.css.ts
  src/app/content/[id]/components/evaluation/RateView/RateList.tsx
  src/app/content/[id]/components/evaluation/Rating/Rating.css.ts
  src/app/content/[id]/components/evaluation/Rating/Rating.tsx
  src/app/content/[id]/components/evaluation/ReactionButtons/ReactionButtons.css.ts
  src/app/content/[id]/components/evaluation/ReactionButtons/ReactionButtons.tsx
  src/app/content/[id]/components/info/InfoContent/InfoContent.css.ts
  src/app/content/[id]/components/info/InfoContent/InfoContent.tsx
  src/app/content/[id]/components/info/InfoHeader/InfoHeader.css.ts
  src/app/content/[id]/components/info/InfoHeader/InfoHeader.tsx
Labels: 🐞 Bug, 혜린

#80 [Feat/#78] View2 하단부 tabBar 추가
  src/app/content/[id]/layout.css.ts
  src/app/content/[id]/layout.tsx
  src/app/content/[id]/page.tsx
  src/shared/components/Bottom/BottomNav.css.ts
Labels: ✨ Feature, 정은

#92 [Feat/#89] view1 api 완료
  next.config.ts
  public/images/view1/boxoffice/img_box office_1.png
  public/images/view1/boxoffice/img_box office_2.png
  public/images/view1/boxoffice/img_box office_3.png
  public/images/view1/series/img_upcoming_series_1.png
  public/images/view1/series/img_upcoming_series_2.png
  public/images/view1/series/img_upcoming_series_3.png
  public/images/view1/series/img_upcoming_series_4.png
  src/app/home/components/MovieCarousel/MovieCarousel.tsx
  src/app/home/components/MovieCarousel/movie/BoxOfficeCarousel.tsx
  src/app/home/components/MovieCarousel/movie/DdayCarousel.tsx
  src/app/home/components/MovieCarousel/movie/SeriesCarousel.tsx
  src/app/home/components/MovieCarousel/movie/TopRankingCarousel.tsx
  src/app/home/page.tsx
  src/app/services/getDday.ts
  src/app/services/getTopRanking.ts
  src/mocks/boxoffice.json
  src/mocks/index.ts
  src/mocks/series.json
  src/shared/widget/MovieCard/MovieCard.css.ts
  src/shared/widget/MovieCard/MovieCard.types.ts
Labels: ✨ Feature, 서연

#94 [Init] git Action 설정
  .github/workflows/main.yml
Labels: ⚙️Environment, 혜린

#99 [Feat/#97] BottomNav 적용 및 스타일링 수정
  next.config.ts
  src/app/content/[id]/review/components/header/Header.tsx
  src/app/content/recommend/components/header/Header.tsx
  src/app/content/recommend/layout.css.ts
  src/app/content/recommend/layout.tsx
  src/app/home/components/MovieCarousel/MovieCarousel.tsx
  src/shared/components/Bottom/BottomNav.css.ts
  src/shared/widget/MovieCard/MovieCard.tsx
Labels: ✨ Feature, 🔨 Refactor, 정은

#102 [Feature/#95] View2 코멘트 조회 API 연동
  src/app/content/[id]/page.tsx
  src/app/content/[id]/sections/comment/CommentSection.tsx
  src/services/content/api.ts
  src/shared/types/detail.ts
Labels: ✨ Feature, 혜린

#111 [Feat/#110] refact header/ view 3 title
  src/app/content/[id]/review/components/header/Header.tsx
  src/shared/components/Header/Header.tsx
  src/shared/components/Header/Tab.ts
  src/shared/widget/MovieCard/MovieMock.ts
Labels: 🔨 Refactor, 윤지

#108 [Refactor/#107] Rating 터치 드래그 이벤트 등록
  src/app/content/[id]/components/Evaluation/Rating/Rating.tsx
Labels: 🔨 Refactor, 정은

#114 [Feat/#109] 에러 및 로딩 핸들링
  package.json
  src/app/content/[id]/components/Evaluation/Rating/Rating.tsx
  src/app/content/[id]/review/page.tsx
  src/app/content/recommend/components/recommendOtt/RecommendOtt.tsx
  src/app/content/recommend/page.tsx
  src/app/error.css.ts
  src/app/error.tsx
  src/app/home/components/MovieCarousel/MovieCarousel.tsx
  src/app/loading.css.ts
  src/app/loading.tsx
  src/app/not-found.css.ts
  src/app/not-found.tsx
  src/app/styles.css.ts
  src/assets/svg/ReIconEye.tsx
  src/assets/svg/ReIconWish.tsx
  src/shared/components/Bottom/BottomNav.tsx
  src/shared/components/Spinner/Spinner.css.ts
  src/shared/components/Spinner/Spinner.tsx
  yarn.lock
Labels: ✨ Feature, 정은

#117 [Refactor/#116] 누락 스타일 추가 및 구조 개선
  src/app/home/Home.css.ts
  src/app/home/components/MovieCarousel/movie/DdayCarousel.tsx
  src/app/home/components/MovieCarousel/movie/TopRankingCarousel.tsx
  src/app/home/components/Section.css.ts
  src/app/home/layout.tsx
  src/app/home/page.tsx
  src/app/services/getTopRanking.ts
  src/services/home/api.ts
Labels: 🔨 Refactor, 정은
